### ISSUE TITLE
Windows tanahelper.exe triggers security thread - Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by hbrns** [verveguy/tana-helper#5]
After the unpacking of the [0.1.0 release](https://github.com/verveguy/tana-helper/releases/download/0.1.0/Tana.Helper.11-win.tar.gz) Windows defender identifies the [Wacatac.B!ml trojan](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Virus:Win32/Wacatac.B!ml&ThreatID=2147774417) in the tanahelper.exe

![image](https://github.com/verveguy/tana-helper/assets/863889/a0bb16ed-a5f8-4efe-bc83-ad01963dbee3)

**Comment by verveguy** [comment]
Crikey! Thx for this report. I've taken down the release while I investigate what is triggering this.

**Comment by verveguy** [comment]
OK. So the good news is that there’s no virus going on here. The problem stems from my use of pyinstaller to build the self-contained .exe. This appears to be a well known problem with pyinstaller bootloader code being flagged as a “viral component” since there are a bunch of viruses out there built with pyinstaller…. ([ref](https://github.com/pyinstaller/pyinstaller/issues/6754) and [ref](https://medium.com/@markhank/how-to-stop-your-python-programs-being-seen-as-malware-bfd7eb407a7) and [ref](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg)

Why didn’t I see this myself? Because most of my build/test activity is on a Windows VM running on my M1 mac and that loader code when built under Intel emulation is different enough that it doesn’t trigger the antivirus pattern match.
But, I switched to an actual Intel Windows machine yesterday to build final packages and … that used the “suspect” pyinstaller bootloader.

It seems that if I rebuild the pyinstaller bootloader from source myself to ensure a different checksum that won’t trip the false positive.

**Comment by verveguy** [comment]
Resolved in new builds.
